### PR TITLE
BLD: Bump the scikit-bio minimum version

### PR DESCRIPTION
**Pull request by ElDeveloper**
As per a conversation with @ebolyen in the forum, I'm bumping the minimum version of scikit-bio to see if hell breaks loose. 🌋 :rage4:

### CODE REVIEW

**Comment by thermokarst** [comment]
🙏 :yoshiki:

**Comment by thermokarst** [comment]
Will merge this and let [busywork](https://busywork.qiime2.org) do its thing. Better grab some popcorn!

If calamity is too crazy, we can always revert the commit produced by merging this PR. Thanks @ElDeveloper  ⚔️  

Also, [forum xref](https://forum.qiime2.org/t/update-scikit-bio-dependency-to-0-5-2-or-newer/4723).

**Comment by thermokarst** [comment]
https://youtu.be/JkK8g6FMEXE

**Comment by ElDeveloper** [comment]
👍 thanks @thermokarst

**Comment by thermokarst** [comment]
Well well well...

https://github.com/qiime2/environment-files/commit/9ad13aeea6f376a6c6a3de597ff49a84040a9b16

Looks like everything worked! Congrats @ElDeveloper, you're my busywork hero! 💪  🍄

**Comment by ElDeveloper** [comment]
Excellent to hear this. Hopefully I can organize a new skbio release once the pcoa biplots get merged and then we can take advantage of the new features.

**Pull request merged**
