### PR TITLE
MAINT: typo in `feature_data_mag/__init__.py`

### PR DESCRIPTION
**Pull request by Sann5**
It looks like all `__init__.py` files import the `_transformer.py` module from their corresponding submodule. However `feature_data_mag/__init__.py` imports the transformer from `feature_data` not `feature_data_mag`. Is this a typo?

### CODE REVIEW

**Review by misialq — APPROVED** [review]
Nice catch @Sann5, thanks!

**Comment by misialq** [comment]
Hey @lizgehret, could you maybe look this over? 🙏

**Comment by lizgehret** [comment]
> Hey @lizgehret, could you maybe look this over? 🙏

You bet! Will take a look right now 🙂

**Review by lizgehret — APPROVED** [review]
fixed some small merge conflicts- looks like we needed to update the imports for all three files (format, transformer, type) rather than just the transformer. thanks for catching this @Sann5! will just wait for ci to pass and then this will be good to merge.

**Pull request merged**
