### PR TITLE
MAINT: migrate q2-demux types/formats/transformers to q2-types for more general access 

### PR DESCRIPTION
**Pull request by hagenjp**
Closes issue [#153](https://github.com/qiime2/q2-demux/issues/153)

### CODE REVIEW

**Review by colinvwood — APPROVED** [review]

**Comment by colinvwood** [comment]
linked to qiime2/q2-demux#160

**Review by lizgehret — COMMENTED** [review]
Hey @hagenjp - tested these changes locally, and they seem reasonable. One thing I noticed is that the number of unit tests that were moved over doesn't match up across repos.

In q2-demux, there were 107 tests prior to your changes, and now there are 88. In q2-types, there were originally 610 tests and now there are 636. So there were 19 tests removed in q2-demux, but 26 tests added in q2-types.

I haven't gone through everything with a fine toothed comb to determine exactly where this discrepancy is coming from - but just wondering if you recall splitting up any tests, or adding any transformers/format validations as tests when migrating everything over to q2-types?

**Comment by hagenjp** [comment]
Hi @lizgehret, I just looked through, I did add 7 tests to match the testing done in q2-types for the transformers. Let me know if you would like me to get rid of those and I can do that. Thanks!

**Comment by lizgehret** [comment]
> Hi @lizgehret, I just looked through, I did add 7 tests to match the testing done in q2-types for the transformers. Let me know if you would like me to get rid of those and I can do that. Thanks!

Hey @hagenjp, thanks for looking into this! No need to get rid of these tests - more is always better, especially when you're matching what we have in our existing test suite! Would you mind adding comments to annotate which tests you added for this purpose? Then this should be g2g 🙂

**Comment by lizgehret** [comment]
Thanks @hagenjp! Okay, it looks like we have one final thing to address - notice that we have test failures occurring on github, but these tests all passed locally for me (and I assume they did for you too). Take a look at the tests that are failing - all related to `file not found` errors. This is a sneaky little gotcha related to your `setup.py` file 🙂 Take a look at that file, and maybe a few other repos' `setup.py` file and see if you can do some detective work there. If you're still unsure after doing some digging, let me know and we can take a look at it together!

**Review by lizgehret — CHANGES_REQUESTED** [review]
Thanks @hagenjp! Okay, it looks like we have one final thing to address - notice that we have test failures occurring on github, but these tests all passed locally for me (and I assume they did for you too). Take a look at the tests that are failing - all related to `file not found` errors. This is a sneaky little gotcha related to your `setup.py` file 🙂 Take a look at that file, and maybe a few other repos' `setup.py` file and see if you can do some detective work there. If you're still unsure after doing some digging, let me know and we can take a look at it together!

**Comment by lizgehret** [comment]
@hagenjp you're on the right track! Take a close look at the particular tests that are failing to help you determine which files aren't being found 🙂

**Review by lizgehret — APPROVED** [review]
nice work @hagenjp! this is good to merge 🙂

**Pull request merged**
